#!/usr/bin/env node
/**
 * Writes eval/reports/current/core-en/summary.md: counts of the core-en circuits, the coverage of the mined mentions and phrases
 * (overall and per area), the validator result, the cross-review rejection rate and the cost per model read from the omp
 * session files of the authoring and review batches.
 */
import {readFileSync, writeFileSync, readdirSync, existsSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import {assemble, loadBatches} from './build.mjs';
import {loadCircuits, lexiconIndex, coverage} from './coverage.mjs';
import {relationRows} from './mine.mjs';
import {phraseKey} from '../../../sop/linking.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const SRC = join(ROOT, 'datasets_sources/core-en');
const OUT = join(ROOT, 'config/knowledge/core-en');

function sessionCost(dir) {
  const sdir = join(dir, '.omp-session');
  let cost = 0, tokens = 0, turns = 0;
  if (!existsSync(sdir)) return {cost, tokens, turns};
  for (const f of readdirSync(sdir).filter(f => f.endsWith('.jsonl'))) {
    for (const l of readFileSync(join(sdir, f), 'utf8').split('\n')) {
      if (!l) continue;
      try { const u = JSON.parse(l).message?.usage; if (u?.cost?.total != null) { cost += u.cost.total; tokens += u.totalTokens ?? 0; turns++; } } catch { /* ignore */ }
    }
  }
  return {cost, tokens, turns};
}
const read = f => existsSync(f) ? readFileSync(f, 'utf8').trim() : '';
const mined = JSON.parse(readFileSync(join(ROOT, 'eval/reports/current/core-en/mined.json'), 'utf8'));
const model = assemble(loadBatches(), {mined});
const areaOf = new Map(model.predicates.map(p => [p.id, p.area]));
const wires = loadCircuits([join(ROOT, 'config/knowledge/core-min'), OUT]);
const index = lexiconIndex(wires);
const rows = relationRows();
const cov = coverage(index, rows);

// per area: mentions whose phrase and role set fit a lexeme, attributed to the area of the best predicate
const perArea = new Map();
let total = 0;
for (const row of rows) for (const m of row.wires) {
  total++;
  const cands = index.forms.get(phraseKey(m.relation)) ?? [];
  const R = new Set(m.roles.map(r => r.name).filter(n => n !== 'time'));
  const fit = cands.filter(c => { const set = new Set(c.frame.split(' ')); return set.size === R.size && [...set].every(r => R.has(r)); });
  const area = fit.length ? (areaOf.get(fit[0].predicate) ?? 'core-min') : (cands.length ? 'phrase only (role set differs)' : 'uncovered');
  perArea.set(area, (perArea.get(area) ?? 0) + 1);
}
const val = spawnSync('node', ['eval/smoke-reasoning/validator.mjs', 'config/knowledge/core-min/0001-upper.sop', ...readdirSync(OUT).filter(f => f.endsWith('.sop')).sort().map(f => 'config/knowledge/core-en/' + f)], {cwd: ROOT, encoding: 'utf8'});
const valLines = (val.stdout + val.stderr).split('\n').filter(Boolean);
const valErrors = valLines.filter(l => !/ warning /.test(l) && !/^OK$/.test(l) && !/problem\(s\)/.test(l));
const dropped = JSON.parse(readFileSync(join(ROOT, 'eval/reports/current/core-en/dropped.json'), 'utf8'));
const byReason = {};
for (const d of dropped) { const k = d.why.replace(/shared with \S+/, 'shared with another predicate').replace(/ \(.*$/, ''); byReason[k] = (byReason[k] ?? 0) + 1; }

const cnt = {predicates: model.predicates.length, variants: model.predicates.filter(p => p.variantOf).length, entities: model.entities.length, rules: model.rules.length, facts: model.facts.length};
let enForms = 0, roForms = 0, lexemes = 0;
for (const p of model.predicates) for (const lx of p.lexemes) { lexemes++; if (lx.language === 'en') enForms += lx.forms.length; else if (lx.language === 'ro') roForms += lx.forms.length; }

const lines = [];
lines.push('# core-en: authoring and coverage summary', '', 'Generated by `tools/linking/core-en/summary.mjs`; regenerable observation.', '');
lines.push('## Content', '', `- predicates: ${cnt.predicates} (${cnt.predicates - cnt.variants} declared, ${cnt.variants} role-set variants), lexemes: ${lexemes}, English forms: ${enForms}${roForms ? `, NON-ENGLISH forms: ${roForms} (the core holds English only; remove them)` : ' (English only, owner decision 2026-10-01)'}`, `- entities: ${cnt.entities} (occupations, properties, units, currencies) plus ${model.classes.length} classes, rules: ${cnt.rules}, facts: ${cnt.facts}`, '');
lines.push('## Validator', '', `Knowledge validator over core-min plus core-en (\`eval/smoke-reasoning/validator.mjs\`): ${valErrors.length ? valErrors.length + ' errors' : 'no errors'}; ${valLines.filter(l => / warning /.test(l)).length} warnings (frame_incomplete, label_collision).`, '');
lines.push('## Coverage of the mined mentions', '', `${cov.mentions} relation mentions in ${cov.rows} rows of symbolic_english and neuro_english (train and dev).`, '', `- phrase has a form: ${cov.phrasePct}%; phrase and role set fit a lexeme: ${cov.framePct}%; exactly one predicate: ${cov.uniquePct}%`, `- rows with every phrase covered: ${cov.rowsPhrasePct}%; every phrase and role set: ${cov.rowsFramePct}%`, `- the bare copula \`be\` (146 mentions) belongs to the copula readings, not to a lexeme`, '', '| area | mentions | share |', '| --- | ---: | ---: |');
for (const [a, n] of [...perArea].sort((x, y) => y[1] - x[1])) lines.push(`| ${a} | ${n} | ${(100 * n / total).toFixed(1)}% |`);
lines.push('', 'Most frequent uncovered phrases:', '', ...cov.uncovered.slice(0, 15).map(u => `- ${u.count} ${u.phrase}`), '');
lines.push('## Cross-review and merge drops', '', ...Object.entries(byReason).map(([k, v]) => `- ${k}: ${v}`), '');
lines.push('## omp batches', '', '| batch | model | cost (nominal USD) | tokens | turns | items |', '| --- | --- | ---: | ---: | ---: | --- |');
const totals = {};
for (const kind of ['tasks', 'review']) for (const area of ['upper', 'place', 'people', 'work', 'study', 'commerce', 'move', 'health', 'talk', 'act']) {
  const dir = join(SRC, kind, area);
  if (!existsSync(dir)) continue;
  const m = read(join(dir, 'output', '.model')) || '?';
  const c = sessionCost(dir);
  const items = kind === 'tasks'
    ? (() => { try { const j = JSON.parse(read(join(dir, 'output', area + '.json'))); return (j.predicates?.length ?? 0) + ' predicates, ' + (j.entities?.length ?? 0) + ' entities'; } catch { return 'n/a'; } })()
    : (() => { try { const n = JSON.parse(read(join(dir, 'output', 'review.json'))).length; const tot = read(join(dir, 'input', 'forms.tsv')).split('\n').length - 1; return tot + ' forms reviewed, ' + n + ' flagged (' + (100 * n / tot).toFixed(1) + '%)'; } catch { return 'no review'; } })();
  lines.push(`| ${kind === 'tasks' ? 'author' : 'review'} ${area} | ${m} | ${c.cost.toFixed(3)} | ${c.tokens} | ${c.turns} | ${items} |`);
  totals[m] = (totals[m] ?? 0) + c.cost;
}
lines.push('', 'Cost per model: ' + Object.entries(totals).map(([m, c]) => `${m} ${c.toFixed(3)}`).join('; ') + '. The cost omp reports is the nominal list price; Grok and GLM run on the owner\'s subscriptions.', '');
writeFileSync(join(ROOT, 'eval/reports/current/core-en/summary.md'), lines.join('\n'));
console.log(lines.join('\n'));
