#!/usr/bin/env node
/** Inspect and export the actual wire/strategy contract. No model is called. */
import fs from 'node:fs';import {SPEC,PROFILE} from '../src/sop/parser.js';import {CAPABILITIES} from '../src/reasoning/registry.js';
const concept=new Set(['fact','rule','event','pattern','hypothesis','action','goal','trace','query','constraint','policy','theory','procedure','template']);
const privileged=new Set(['rule','action','procedure','template','policy','theory','binding']);
const roles={fact:'admitted-claim',rule:'approved-implication',event:'claim-update',pattern:'candidate-regularity',hypothesis:'candidate-assumptions',action:'state-transition',goal:'desired-state',trace:'case-evidence',query:'logical-goal',constraint:'numeric-problem',policy:'host-budget-restriction',theory:'requires-extension-compiler',procedure:'approved-subcircuit',template:'approved-subcircuit'};
const result={profile:PROFILE,memoryEngines:['weaver','holo','sqlite','scan','hybrid'],reasoning:CAPABILITIES,wires:Object.fromEntries(Object.entries(SPEC).map(([name,s])=>[name,{...s,role:roles[name]??'operation',declaration:concept.has(name),authoredByModel:!privileged.has(name),effects:name==='assert'?'explicit-session-write':name==='reason'?'may-reinforce-nonhypothetical-observed-proof':'no-world-write',note:name==='trace'?'Model cannot certify closed=true':name==='binding'?'Runtime-generated only':name==='theory'?'Unsupported unless an approved strategy handles the dialect':undefined}]))};
if(process.argv.includes('--write')){fs.mkdirSync('docs/contracts',{recursive:true});fs.writeFileSync('docs/contracts/wires.json',JSON.stringify(result,null,2)+'\n');let text='# Câmpurile acceptate în '+PROFILE+'\n\nGenerat de `node tools/capabilities.js --write` din parser și registrul engine-ului. Cardinalitatea «unic» înseamnă maximum o apariție; câmpurile obligatorii sunt precizate separat. Validarea semantică descrisă în capitolul 24 se aplică suplimentar.\n\n';for(const [name,s]of Object.entries(result.wires)){text+='## `'+name+'`\n\n';text+='Câmpuri unice: '+(s.one?.map(x=>'`'+x+'`').join(', ')||'niciunul')+'.\n\nRepetabile: '+(s.many?.map(x=>'`'+x+'`').join(', ')||'niciunul')+'.\n\nObligatorii: '+(s.required?.map(x=>'`'+x+'`').join(', ')||'conform validării semantice')+'.\n\nModelul poate declara acest tip: '+(s.authoredByModel?'da, sub policy-ul host-ului':'nu; definiție aprobată sau fir intern')+'. '+(s.note??'')+'\n\n';}fs.writeFileSync('docs/contracts/wire-fields.md',text);}
console.log(JSON.stringify(result,null,2));
