#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {cliArgs,readJSONL,assert,saveJSON,digest} from '../src/util.js';import {parse,canonical} from '../src/sop/parser.js';
import {Repository} from '../src/repository.js';import {Runtime} from '../src/runtime.js';import {Lexicon} from '../src/lexicon.js';import {publishKnowledge} from '../src/ingest.js';
const args=cliArgs(),dir=path.resolve(args.dir??'data/generated'),execute=args.execute===true,max=Number(args.limit??1000000),lex=Lexicon.load(new URL('../config/ontology.sop',import.meta.url));
const groups=new Map(),prompts=new Map(),counts={},failures=[];let checked=0,executed=0;const root=fs.mkdtempSync(path.join(os.tmpdir(),'sop-data-')),memory={power:8,engine:args.engine??'weaver',holo:{rows:256,banks:4,dimension:64},...(args.sharded?{sharding:{enabled:true,mode:'archive',maxClaimsPerShard:4,gcEveryWrites:0}}:{})},repo=new Repository(root,{memory}),bases=new Set();
try{for(const role of ['formalizer','verbalizer'])for(const split of ['train','dev','test']){const rows=readJSONL(path.join(dir,role,split+'.jsonl'));counts[role+'/'+split]=rows.length;for(const row of rows){checked++;const ph=digest([role,row.prompt]);assert(!prompts.has(ph)||prompts.get(ph)===split,'Identical prompt leaked across splits');prompts.set(ph,split);assert(row.profile==='sop-agent-3','Wrong dataset profile');assert(typeof row.prompt==='string'&&typeof row.target==='string','Missing prompt/target');const old=groups.get(row.group);assert(!old||old===split,'World leakage between splits: '+row.group);groups.set(row.group,split);
  try{if(role==='formalizer'){assert(canonical(parse(row.target))===row.target,'SOP is not canonical');if(execute&&executed<max){if(!bases.has(row.group)){publishKnowledge(repo,row.group,row.setup_sop,{schema:lex.predicates,memory,knownAt:Date.parse('2024-01-01'),reviewed:true});bases.add(row.group);}const session=repo.session(row.group,'validation',row.id);const result=await new Runtime({repo,session,schema:lex.predicates,now:Date.parse('2026-09-26T12:00:00Z')}).run(row.target,{origin:'model'});const packet=result.result?.packet??result.result;if(row.expectedStatus)assert(packet.status===row.expectedStatus,`Expected ${row.expectedStatus}, got ${packet.status}`);for(const [name,status]of Object.entries(row.expectedOutputs??{}))assert(result.outputs[name]?.status===status,`Output ${name}: expected ${status}, got ${result.outputs[name]?.status}`);const c=row.expectedCheck??{};if(c.output)assert(result.values[c.output]===c.value,'Unexpected exported value');if(c.objective!==undefined)assert(packet.objective===c.objective,'Unexpected optimum');if(c.explanations)assert(packet.explanations.length===c.explanations,'Wrong number of explanations');if(c.testRecommended)assert(packet.nextTest,'Missing test suggestion');if(c.firstCandidate)assert(packet.candidates[0].id===c.firstCandidate,'Wrong best case');if(c.counterexamples)assert(packet.patterns[0].training.counterexamples===c.counterexamples,'Wrong counterexamples');if(c.mappingScore)assert(packet.mappings[0].score===c.mappingScore,'Wrong analogy');if(c.planCost)assert(packet.plans[0].cost===c.planCost,'Wrong plan cost');if(c.hypothetical)assert(packet.hypothetical,'Missing hypothetical marker');if(c.factualStatus)assert(packet.factualStatus===c.factualStatus,'Wrong baseline status');executed++;}}}
  catch(e){failures.push({id:row.id,error:e.message});}
 }}}
finally{fs.rmSync(root,{recursive:true,force:true});}
const report={profile:'sop-agent-3',engine:args.engine??'weaver',memoryProfile:args.sharded?'sharded-archive':'legacy',checked,executed,groups:groups.size,counts,failures,neuralModelTested:false};if(args.out)saveJSON(args.out,report);console.log(JSON.stringify(report,null,2));if(failures.length)process.exitCode=1;
