#!/usr/bin/env node
/** Offline verification. Does not install packages, download weights or train. */
import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {saveJSON,digest} from '../src/util.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');process.chdir(root);fs.mkdirSync('reports',{recursive:true});
const group=process.argv.includes('--group')?process.argv[process.argv.indexOf('--group')+1]:'all';
const directories=['src','tests','tools','training','config','prompts','data/seed','examples'];function fingerprints(dir){return fs.readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name)).flatMap(e=>{const p=path.join(dir,e.name);if(e.name==='__pycache__')return [];return e.isDirectory()?fingerprints(p):[[p,digest(fs.readFileSync(p))]];});}const sourceFingerprint=digest(directories.flatMap(fingerprints));
const results=[],testFiles=fs.readdirSync('tests').filter(x=>x.endsWith('.test.js')).sort().map(x=>'tests/'+x);
const jobs=[['node-tests',process.execPath,['--test',...testFiles]],['demo',process.execPath,['examples/demo.js']],['linker-demo',process.execPath,['examples/linker-demo.js']],['forgetting-demo',process.execPath,['examples/forgetting-demo.js']],['shards-demo',process.execPath,['examples/shards-demo.js']],['shards-benchmark',process.execPath,['tools/bench-shards.js']],['data-validation',process.execPath,['tools/check-data.js','--dir','data/seed','--execute','--out','reports/data-validation.json']],['data-sharded',process.execPath,['tools/check-data.js','--dir','data/seed','--execute','--sharded','--out','reports/data-sharded.json']],['solver-availability',process.execPath,['tools/check-solvers.js']]];
jobs.push(['reasoning-matrix',process.execPath,['examples/reasoning-demo.js']]);
jobs.push(['contracts',process.execPath,['tools/capabilities.js']]);
jobs.push(['memory-demo',process.execPath,['examples/memory-demo.js']]);
for(const engine of ['holo','sqlite','scan','hybrid'])jobs.push(['data-'+engine,process.execPath,['tools/check-data.js','--dir','data/seed','--execute','--engine',engine,'--out','reports/memory/data-'+engine+'.json']]);
const python=process.env.PYTHON??'python3',hasPython=spawnSync(python,['--version'],{encoding:'utf8'}).status===0;
if(hasPython){jobs.push(['training-format',python,['-m','unittest','discover','-s','tests','-p','test_*.py']],['formalizer-dry-run',python,['training/train.py','--role','formalizer','--data','data/seed','--dry-run']],['verbalizer-dry-run',python,['training/train.py','--role','verbalizer','--data','data/seed','--dry-run']]);}
else results.push({name:'training-python',status:'skipped',reason:'Python not installed; Node runtime still testable'});
const groups={core:jobs.filter(j=>!j[0].startsWith('data-')&&!['training-format','formalizer-dry-run','verbalizer-dry-run'].includes(j[0])), 'associative-data':jobs.filter(j=>['data-validation','data-sharded','data-holo'].includes(j[0])), 'exact-data':jobs.filter(j=>['data-sqlite','data-scan','data-hybrid'].includes(j[0])),python:jobs.filter(j=>['training-format','formalizer-dry-run','verbalizer-dry-run'].includes(j[0]))};
if(process.argv.includes('--collect')){const parts=Object.keys(groups).map(g=>JSON.parse(fs.readFileSync('reports/verification-'+g+'.json','utf8')));if(parts.some(p=>p.sourceFingerprint!==sourceFingerprint||!p.complete))throw Error('Stale/incomplete verification part; re-run changed source');const combined=parts.flatMap(p=>p.results),r={profile:'sop-agent-3',node:process.version,platform:process.platform,arch:process.arch,sourceFingerprint,complete:true,neuralModelTested:false,trainingExecuted:false,results:combined};saveJSON('reports/verification.json',r);console.log(JSON.stringify(r,null,2));process.exit(combined.some(p=>p.status==='failed')?1:0);}
if(group!=='all'&&!groups[group])throw Error('Unknown --group '+group);const selectedJobs=group==='all'?jobs:groups[group],reportPath='reports/verification'+(group==='all'?'':'-'+group)+'.json';
for(const [name,cmd,args]of selectedJobs){console.log('START '+name);const start=performance.now(),r=spawnSync(cmd,args,{encoding:'utf8',timeout:name.includes('dry-run')||name==='training-format'?15000:180000,maxBuffer:20*1024*1024});const log=(r.stdout??'')+(r.stderr??'');fs.writeFileSync('reports/'+name+'.log',log);const entry={name,status:r.status===0?'passed':'failed',exitCode:r.status,seconds:Number(((performance.now()-start)/1000).toFixed(3)),error:r.error?.message??null};if(name==='node-tests'){for(const key of ['tests','pass','fail','skipped']){const m=log.match(new RegExp('^# '+key+' (\\d+)$','m'));if(m)entry[key]=Number(m[1]);}}results.push(entry);console.log(name+': '+entry.status+' ('+entry.seconds+'s)');saveJSON(reportPath,{sourceFingerprint,profile:'sop-agent-3',node:process.version,complete:false,neuralModelTested:false,trainingExecuted:false,results});}
const summary={sourceFingerprint,profile:'sop-agent-3',node:process.version,platform:process.platform,arch:process.arch,complete:true,neuralModelTested:false,trainingExecuted:false,results};saveJSON(reportPath,summary);console.log(JSON.stringify(summary,null,2));if(results.some(x=>x.status==='failed'))process.exitCode=1;
