#!/usr/bin/env node
/**
 * The small-talk collections of the conversation layer (owner request of 2026-10-02; DS022 "Composing a base memory", DS023
 * "Conversation layer"). Deterministic code only: the taxonomy (tools/smalltalk/taxonomy.json) gives the situations, their
 * triggers, priorities, slots and registers; the reply texts come from the accepted records of jobs/smalltalk-replies runs
 * (generated by a cheap tier, reviewed in bulk by the auditor tier, fixes decided by the decider tier); this script filters them
 * for diversity and writes the collections as seed layers of config/knowledge/.
 *
 *   node tools/smalltalk/build.mjs items                          the generation items (JSONL on stdout; the job's inputs.command)
 *   node tools/smalltalk/build.mjs write --runs DIR[,DIR...] [--drop FILE]
 *                                                                 writes config/knowledge/smalltalk-<name>-v1/ from the runs' accepted
 *                                                                 records (a later run's item replaces an earlier one); --drop names a
 *                                                                 JSON list of variant texts to leave out (escalation decisions)
 *   node tools/smalltalk/build.mjs acts                           writes only the message acts of the collections (0005-acts.sop) and
 *                                                                 their manifests' `acts` (P-2.1); no run is needed
 *   node tools/smalltalk/build.mjs check                          validates every collection alone and all together, checks slots,
 *                                                                 reachability and priority ties; exit 1 on a problem
 *
 * Registers (P-2.2, 2026-10-03): neutral and warm variants go to the situation's own collection; playful ones of a playful situation
 * stay there; playful ones of another situation go to smalltalk-playful-v1 as a variant situation `<situation>_playful`, and formal
 * ones to smalltalk-professional-v1 as `<situation>_formal`, one priority above the base, derived by that collection's rule only while
 * the conversation's register is playful or formal (`cv_register`, from the user's instruction or a deployment rule).
 * Message acts (P-2.1): the taxonomy's `acts` are written as facts (cv_act, cv_act_description, cv_act_example, cv_act_standalone) into
 * the collection whose situation the act triggers. Ties (P-2.4): two act-triggered situations of one part with the same priority get a
 * `cv_situation_outranks` fact (taxonomy `tie_rank`, else taxonomy order); a register variant that ties with another situation is
 * outranked by it.
 */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {validateProgram, parse} from '../../sop/knowledge/index.mjs';
import {SEEDS_DIR, seedLayers, seedCircuits} from '../../lib/knowledge-seeds.mjs';
import {variantProblems} from '../../jobs/smalltalk-replies/checks.mjs';

const ROOT = fileURLToPath(new URL('../../', import.meta.url));
export const TAXONOMY = JSON.parse(fs.readFileSync(new URL('./taxonomy.json', import.meta.url), 'utf8'));
export const REGISTERS = {n: 'neutral', w: 'warm', p: 'playful', f: 'formal'};
/** The collections: folder id, wire id prefix, name and description. */
export const COLLECTIONS = {
  core: {id: 'smalltalk-core-v1', prefix: 'stc', name: 'Small talk: core (English)', description: 'Greetings and farewells, thanks, apologies, how-are-you, weather, weekend, hobbies and sport chat, compliments, acknowledgements, clarification and repair, and small talk that leads back to useful help; neutral and warm registers. More variants for the situations of conversation-v1 and new situations triggered by pragmatic kinds.'},
  empathy: {id: 'smalltalk-empathy-v1', prefix: 'ste', name: 'Small talk: empathy (English)', description: 'Replies to feelings shown in a message without a request: frustration, sadness, joy, grief, loneliness, stress, fear, anger, disappointment, embarrassment, tiredness, pride, excitement, nostalgia, surprise, and a crisis reply that points to emergency help; neutral and warm registers.'},
  self: {id: 'smalltalk-self-v1', prefix: 'sts', name: 'Small talk: the assistant itself (English)', description: 'Honest replies about the assistant (who it is, what it can do and knows, no feelings, not human, no internet, no memory beyond the conversation and its base memory, how it works), opinion and advice requests framed honestly, off-topic tasks, manipulation attempts, paradoxes, impossible premises, nonsense hypotheticals, offensive messages and possible irony.'},
  playful: {id: 'smalltalk-playful-v1', prefix: 'stp', name: 'Small talk: playful (English)', description: 'Jokes and riddles, replies to laughter and playful teasing, and playful variants that join the light situations of the other collections (greetings, thanks, goodbyes, how-are-you, compliments).'},
  professional: {id: 'smalltalk-professional-v1', prefix: 'stf', name: 'Small talk: professional register (English)', description: 'The formal register: a formal variant of every situation that has one, one priority above its base situation, so that with this collection loaded the formal phrasing wins. Load at most one register collection that overrides (this one).'},
};
const REQUIRES = {core: [], empathy: [], self: [], playful: [], professional: []};
const CONVERSATION = 'conversation-v1';
const LICENCE = 'MIT (repository LICENSE); original ChatSOP text written by model runs of jobs/smalltalk-replies and reviewed automatically';
export const INSPIRED_BY = [
  {source: 'DailyDialog', use: 'topic categories and dialogue-act types (inform, question, directive, commissive) as ideas'},
  {source: 'EmpatheticDialogues', use: 'the set of 32 emotion labels, grouped into the empathy situations'},
  {source: 'MultiWOZ', use: 'general dialogue acts (greet, bye, thank, welcome, reqmore) as ideas'},
  {source: 'Wizard of Wikipedia', use: 'chit-chat about a topic that leads to knowledge, as an idea'},
  {source: 'Cornell Movie-Dialogs Corpus', use: 'turn patterns of casual conversation, as an idea'},
];

const opt = (args, n, d = null) => { const i = args.indexOf(`--${n}`); return i >= 0 ? args[i + 1] : d; };
const CONTEXT = {
  body: 'the whole reply to the message: nothing else is said in this turn',
  opening: 'the first words of a reply; the answer to the user\'s request follows right after it in the same message, so answer nothing yourself and ask no question',
  closing: 'the last sentence of a reply, after the answer',
  follow_up: 'a sentence after the answer, before any closing',
  aside: 'a short lead-in placed after the answer, followed directly by a fact sentence',
};
const DEFAULT_MAX = {body: 200, opening: 60, closing: 160, follow_up: 160, aside: 80};

/** The generation items of the taxonomy. */
export function items(taxonomy = TAXONOMY) {
  return taxonomy.situations.map(s => {
    const allowed = s.slots ?? [], required = s.required ?? [];
    const maxLen = s.max ?? DEFAULT_MAX[s.part];
    const registerNames = s.registers.map(r => REGISTERS[r]);
    const count = s.n ?? 3;
    return {
      id: s.id, situation: s.id, part: s.part, describe: s.describe, context: CONTEXT[s.part],
      registers: registerNames.join(', '), registerNames, count, allowed, required, maxLen, ends: s.ends ?? null,
      slots: allowed.length ? allowed.map(x => `{{${x}}} (${required.includes(x) ? 'required' : 'optional'})`).join(', ') : 'none: use no placeholder',
      length: `at most ${maxLen} characters`,
      shape: s.shape ?? (s.ends ? `the text must end with ${JSON.stringify(s.ends)}` : 'free'),
      facts: taxonomy.system_facts.map(f => `- ${f}`).join('\n'),
    };
  });
}

// --- diversity (deterministic): normalized tokens, distinct-n, near duplicates
const tokens = text => String(text).toLowerCase().replace(/\{\{[a-z_]+\}\}/g, ' slot ').replace(/[^a-z0-9' ]+/g, ' ').split(/\s+/).filter(Boolean);
const ngrams = (toks, n) => toks.slice(0, Math.max(0, toks.length - n + 1)).map((_, i) => toks.slice(i, i + n).join(' '));
/** distinct-n over a list of texts: unique n-grams / all n-grams. */
export function distinct(texts, n) {
  const all = texts.flatMap(t => ngrams(tokens(t), n));
  return all.length ? new Set(all).size / all.length : 0;
}
const jaccard = (a, b) => { const A = new Set(a), B = new Set(b); let i = 0; for (const x of A) if (B.has(x)) i += 1; return A.size + B.size ? i / (A.size + B.size - i) : 0; };
/** Two texts are near duplicates when their word sets or their word bigrams overlap heavily. */
export function nearDuplicate(a, b) {
  const ta = tokens(a), tb = tokens(b);
  if (ta.join(' ') === tb.join(' ')) return true;
  return jaccard(ta, tb) >= 0.7 || (ta.length > 3 && tb.length > 3 && jaccard(ngrams(ta, 2), ngrams(tb, 2)) >= 0.5);
}
/** Keeps texts in order, dropping each that is a near duplicate of one kept or of a reference text; at most `cap`. */
export function diverse(texts, {cap = Infinity, reference = []} = {}) {
  const kept = [], dropped = [];
  for (const t of texts) {
    if (kept.length >= cap || [...kept, ...reference].some(k => nearDuplicate(k, t))) dropped.push(t);
    else kept.push(t);
  }
  return {kept, dropped};
}

/** Accepted variants of the runs: [{situation, register, text, run, model}]; a later run's item replaces an earlier one. */
export function runVariants(dirs) {
  const byItem = new Map();
  for (const dir of dirs) {
    const run = path.basename(dir);
    const file = path.join(dir, 'accepted.jsonl');
    if (!fs.existsSync(file)) throw new Error(`no accepted.jsonl in ${dir}`);
    const last = new Map();
    for (const line of fs.readFileSync(file, 'utf8').split('\n').filter(Boolean)) { const r = JSON.parse(line); last.set(r.id, r); }
    // An item the audit flagged and the decider could not fix is left out (a later run, e.g. a stronger tier, may supply it).
    const escalated = new Set((fs.existsSync(path.join(dir, 'escalations.jsonl')) ? fs.readFileSync(path.join(dir, 'escalations.jsonl'), 'utf8').split('\n').filter(Boolean).map(l => JSON.parse(l)) : []).filter(e => e.source === 'audit').map(e => e.id));
    for (const id of escalated) last.delete(id);
    for (const [id, r] of last) byItem.set(id, (r.output?.records ?? []).filter(x => typeof x.text === 'string').map(x => ({situation: id, register: x.register, text: clean(x.text), run, model: r.model ?? null})));
  }
  return [...byItem.values()].flat();
}
const clean = t => String(t).replace(/[‘’]/g, "'").replace(/[“”]/g, '"').replace(/—/g, ' - ').replace(/–/g, '-').replace(/…/g, '...').replace(/[ \t]+/g, ' ').trim();

/** The existing replies of conversation-v1, by situation (the reference for near duplicates) and its situation priorities. */
export function conversationLayer() {
  const text = seedCircuits(CONVERSATION).map(c => c.text).join('\n');
  const replies = new Map(), priorities = new Map(), parts = new Map();
  for (const w of parse(text).wires) {
    if (w.type !== 'reply') continue;
    const f = k => w.fields.find(x => x.key === k)?.value.trim();
    const s = f('situation');
    parts.set(s, f('part') ?? 'body');
    if (!replies.has(s)) replies.set(s, []);
    replies.get(s).push(JSON.parse(f('text')));
  }
  for (const m of text.matchAll(/holds cv_situation_priority (\w+) (-?\d+)/g)) priorities.set(m[1], Number(m[2]));
  return {replies, priorities, parts, signalled: signalledSituations(text)};
}

/**
 * The situations of a layer text that a message act selects: named by a cv_courtesy_situation, cv_opening_situation or
 * cv_closing_situation fact, or concluded by a rule that tests cv_turn_signal. Two of them can apply to one turn, so a tie between them
 * must be ordered (P-2.4). In text order.
 */
export function signalledSituations(text) {
  const out = [];
  const add = s => { if (!out.includes(s)) out.push(s); };
  for (const m of text.matchAll(/holds cv_(?:courtesy|opening|closing)_situation \w+ (\w+)|@\S+ rule\n((?:  .*\n)+)/g)) {
    if (m[1]) add(m[1]);
    else if (/when cv_turn_signal /.test(m[2])) for (const t of m[2].matchAll(/then cv_applies (\w+)/g)) add(t[1]);
  }
  return out;
}

const q = s => JSON.stringify(s);
const replyWire = (id, situation, part, text, source) => `@${id} reply\n  situation ${situation}\n  part ${part}\n  language en\n  text ${q(text)}\n  source ${q(source)}\n`;
const fact = (id, atom) => `@${id} fact\n  holds ${atom}\n`;

/** Builds the collections' files from the variants: {collectionKey: {files: {name: text}, counts, report}}. */
export function buildCollections(variants, {taxonomy = TAXONOMY, drop = []} = {}) {
  const conv = conversationLayer();
  const bySituation = new Map(taxonomy.situations.map(s => [s.id, s]));
  const dropSet = new Set(drop.map(clean));
  const out = Object.fromEntries(Object.keys(COLLECTIONS).map(k => [k, {data: [], replies: [], rules: [], counts: {situations: new Set(), replies: 0, registers: {}}, diversity: []}]));
  const priorityOf = s => s.priority ?? conv.priorities.get(s.id);
  // Trigger data and priorities of the new situations (in the situation's own collection).
  for (const s of taxonomy.situations) {
    const c = out[s.collection], pre = COLLECTIONS[s.collection].prefix;
    const t = s.trigger;
    if (t.type === 'existing') continue;
    c.data.push(fact(`${pre}_p_${s.id}`, `cv_situation_priority ${s.id} ${s.priority}`));
    if (t.type === 'courtesy') c.data.push(fact(`${pre}_k_${s.id}`, `cv_courtesy_situation ${t.kind} ${s.id}`));
    if (t.type === 'opening') c.data.push(fact(`${pre}_k_${s.id}`, `cv_opening_situation ${t.kind} ${s.id}`));
    if (t.type === 'closing') c.data.push(fact(`${pre}_k_${s.id}`, `cv_closing_situation ${t.kind} ${s.id}`));
    if (t.type === 'topics_of') {
      const kind = bySituation.get(t.of).trigger.kind;
      c.rules.push(`# ${s.id}: the reply to ${t.of} when the memory's topics are known (slot topics).\n@${pre}_r_${s.id} rule\n  when cv_courtesy_only\n  when cv_turn_signal ${kind}\n  when cv_turn_topics\n  then cv_applies ${s.id}\n`);
    }
  }
  // Reply variants, by situation and register group, filtered for diversity.
  const groups = new Map();
  const itemOf = new Map(items(taxonomy).map(it => [it.id, it]));
  for (const v of variants) {
    const s = bySituation.get(v.situation);
    if (!s || dropSet.has(v.text) || variantProblems(itemOf.get(s.id), v).length) continue;
    const key = v.register === 'formal' ? 'professional' : v.register === 'playful' && s.collection !== 'playful' ? 'playful' : s.collection;
    // A register variant of another collection's situation is its own situation (`<situation>_formal`, `<situation>_playful`).
    const g = `${key}\u0000${s.id}`;
    if (!groups.has(g)) groups.set(g, {key, s, variants: []});
    groups.get(g).variants.push(v);
  }
  const registerVariants = [];
  const variantOf = (key, s) => (key === 'professional' ? `${s.id}_formal` : key === 'playful' && s.collection !== 'playful' ? `${s.id}_playful` : null);
  for (const {key, s, variants: vs} of [...groups.values()].sort((a, b) => a.s.id.localeCompare(b.s.id) || a.key.localeCompare(b.key))) {
    const c = out[key], pre = COLLECTIONS[key].prefix;
    const situation = variantOf(key, s) ?? s.id;
    const cap = (s.n ?? 3) * (key === s.collection ? s.registers.filter(r => r === 'n' || r === 'w' || (s.collection === 'playful' && r === 'p')).length : 1);
    const registers = [...new Set(vs.map(v => v.register))];
    // Interleave registers so the cap keeps a balance between them.
    const ordered = [];
    for (let i = 0; ordered.length < vs.length; i++) for (const r of registers) { const x = vs.filter(v => v.register === r)[i]; if (x) ordered.push(x); }
    const {kept, dropped} = diverse(ordered.map(v => v.text), {cap, reference: conv.replies.get(s.id) ?? []});
    const meta = new Map(ordered.map(v => [v.text, v]));
    kept.forEach((text, i) => {
      const v = meta.get(text);
      c.replies.push(replyWire(`${pre}_${situation}_${i + 1}`, situation, s.part, text, `jobs/smalltalk-replies run ${v.run}${v.model ? ` (${v.model})` : ''}; register ${v.register}; reviewed by the auditor tier`));
      c.counts.registers[v.register] = (c.counts.registers[v.register] ?? 0) + 1;
    });
    c.counts.replies += kept.length;
    if (kept.length) c.counts.situations.add(situation);
    c.diversity.push({situation, candidates: vs.length, kept: kept.length, near_duplicates_dropped: dropped.length, distinct_1: round(distinct(kept, 1)), distinct_2: round(distinct(kept, 2))});
    if (situation !== s.id && kept.length) registerVariants.push({key, base: s.id, variant: situation, priority: priorityOf(s) + 1, part: s.part});
  }
  // The register collections: the variant table, the rule (only while the conversation's register is theirs) and the priorities.
  for (const [key, register, predicate] of [['professional', 'formal', 'st_formal_variant'], ['playful', 'playful', 'st_playful_variant']]) {
    const c = out[key], pre = COLLECTIONS[key].prefix;
    c.vocabulary = `@${predicate} predicate\n  args subject:entity object:entity\n  closed true\n  description "the situation (object) is the ${register}-register variant of the situation (subject); while the register is ${register} it applies whenever the subject applies and outranks it by one"\n`;
    c.rules.push(`# The ${register} register: while the conversation's register is ${register}, whenever a situation applies its ${register} variant applies too, one priority higher, so it wins its part.\n@${pre}_r_${register} rule\n  when cv_register ${register}\n  when cv_applies ?s\n  when ${predicate} ?s ?v\n  then cv_applies ?v\n`);
    c.rules.push(`# Two variants tie as their bases do: the variant of the base that outranks the other outranks it too.\n@${pre}_r_${register}_ties rule\n  when ${predicate} ?a ?v\n  when ${predicate} ?b ?w\n  when cv_situation_outranks ?a ?b\n  then cv_situation_outranks ?v ?w\n`);
    for (const f of registerVariants.filter(x => x.key === key)) {
      c.data.push(fact(`${pre}_v_${f.base}`, `${predicate} ${f.base} ${f.variant}`));
      c.data.push(fact(`${pre}_p_${f.base}`, `cv_situation_priority ${f.variant} ${f.priority}`));
    }
  }
  // Ties (P-2.4): act-triggered situations of one part with one priority are ordered by data; a register variant that ties with
  // another situation of its part is outranked by it (the other's base priority is the higher one).
  const priorities = new Map([...conv.priorities, ...taxonomy.situations.filter(s => s.priority !== undefined).map(s => [s.id, s.priority])]);
  const parts = new Map([...conv.parts, ...taxonomy.situations.map(s => [s.id, s.part])]);
  // Contenders: the act-selected situations of conversation-v1 (ranked first, in its order) and of the taxonomy (tie_rank, else order).
  const triggered = [...conv.signalled.map((id, i) => ({id, part: conv.parts.get(id), priority: conv.priorities.get(id), rank: i, collection: null})),
    ...taxonomy.situations.filter(s => ['courtesy', 'opening', 'closing', 'topics_of'].includes(s.trigger.type)).map((s, i) => ({id: s.id, part: s.part, priority: priorityOf(s), rank: s.tie_rank ?? 100 + i, collection: s.collection}))];
  for (const a of triggered) for (const b of triggered) {
    if (a === b || a.part !== b.part || a.priority !== b.priority || a.rank >= b.rank) continue;
    // A pair of conversation-v1's own situations is ordered by conversation-v1's data; any other pair by the collection of either.
    const owner = a.collection ?? b.collection;
    if (owner) out[owner].data.push(fact(`${COLLECTIONS[owner].prefix}_o_${a.id}__${b.id}`, `cv_situation_outranks ${a.id} ${b.id}`));
  }
  for (const v of registerVariants) for (const [x, p] of priorities) {
    if (p !== v.priority || parts.get(x) !== v.part || x === v.variant) continue;
    out[v.key].data.push(fact(`${COLLECTIONS[v.key].prefix}_o_${x}__${v.variant}`, `cv_situation_outranks ${x} ${v.variant}`));
  }
  return out;
}

/** The message acts of the taxonomy as facts, per collection key (the collection whose situation the act triggers). */
export function actsByCollection(taxonomy = TAXONOMY) {
  const out = Object.fromEntries(Object.keys(COLLECTIONS).map(k => [k, []]));
  for (const a of taxonomy.acts ?? []) {
    const s = taxonomy.situations.find(x => x.trigger.kind === a.kind && x.trigger.proposed) ?? taxonomy.situations.find(x => x.trigger.kind === a.kind);
    if (!s) throw new Error(`the act ${a.kind} triggers no situation of the taxonomy`);
    const pre = COLLECTIONS[s.collection].prefix;
    const lines = [fact(`${pre}_a_${a.kind}`, `cv_act ${a.kind} ${a.group}`), fact(`${pre}_a_${a.kind}_d`, `cv_act_description ${a.kind} ${q(a.describe)}`),
      ...(a.examples ?? []).map((e, i) => fact(`${pre}_a_${a.kind}_e${i + 1}`, `cv_act_example ${a.kind} ${q(e)}`)),
      ...(a.standalone ? [fact(`${pre}_a_${a.kind}_s`, `cv_act_standalone ${a.kind}`)] : [])];
    out[s.collection].push({kind: a.kind, group: a.group, situation: s.id, text: lines.join('')});
  }
  return out;
}

/** Writes the collections' 0005-acts.sop and the manifests' `acts` (the declared kinds). */
export function writeActs(taxonomy = TAXONOMY) {
  const byCollection = actsByCollection(taxonomy);
  for (const [key, acts] of Object.entries(byCollection)) {
    const info = COLLECTIONS[key], dir = path.join(SEEDS_DIR, info.id);
    const file = path.join(dir, '0005-acts.sop');
    if (!acts.length) { fs.rmSync(file, {force: true}); continue; }
    fs.writeFileSync(file, `# ${info.id}: the message acts this collection answers (P-2.1; declared as data, read by the formalizer and the validator: sop/message-acts.mjs).\n# Generated by tools/smalltalk/build.mjs from tools/smalltalk/taxonomy.json (acts); do not edit by hand.\n\n` + acts.map(a => a.text).join('\n'));
    const manifestFile = path.join(dir, 'seed.json');
    const manifest = JSON.parse(fs.readFileSync(manifestFile, 'utf8'));
    delete manifest.proposed_kinds;
    manifest.acts = acts.map(a => ({kind: a.kind, group: a.group, situation: a.situation}));
    fs.writeFileSync(manifestFile, JSON.stringify(manifest, null, 2) + '\n');
  }
}
const round = x => Math.round(x * 1000) / 1000;

/** Writes the collections' folders (seed.json and circuits) and returns their manifests. */
export function writeCollections(built, {runs = []} = {}) {
  const manifests = {};
  for (const [key, c] of Object.entries(built)) {
    const info = COLLECTIONS[key];
    const dir = path.join(SEEDS_DIR, info.id);
    fs.rmSync(dir, {recursive: true, force: true});
    fs.mkdirSync(dir, {recursive: true});
    const head = `# ${info.id}: ${info.description}\n# Generated by tools/smalltalk/build.mjs from tools/smalltalk/taxonomy.json and the accepted records of jobs/smalltalk-replies; do not edit by hand.\n\n`;
    if (c.vocabulary) fs.writeFileSync(path.join(dir, '0001-vocabulary.sop'), head + c.vocabulary);
    if (c.data.length || c.rules.length) fs.writeFileSync(path.join(dir, '0010-situations.sop'), head + [...c.rules, ...c.data].join('\n'));
    fs.writeFileSync(path.join(dir, '0020-replies.sop'), head + c.replies.join('\n'));
    const d1 = c.diversity.filter(x => x.kept > 1);
    const manifest = {
      name: info.name, description: info.description, imports: [CONVERSATION], role: 'conversation', ...(key === 'professional' ? {group: 'register'} : {}),
      licence: LICENCE,
      provenance: {generator: 'jobs/smalltalk-replies (worker tier, bulk audit by the auditor tier, decider tier for fixes)', builder: 'tools/smalltalk/build.mjs', taxonomy: 'tools/smalltalk/taxonomy.json', runs, inspired_by: INSPIRED_BY.map(x => ({...x, text_copied: false}))},
      counts: {situations: c.counts.situations.size, replies: c.counts.replies, by_register: c.counts.registers, rules: c.rules.length, data_facts: c.data.length,
        mean_distinct_1: round(d1.reduce((a, x) => a + x.distinct_1, 0) / (d1.length || 1)), mean_distinct_2: round(d1.reduce((a, x) => a + x.distinct_2, 0) / (d1.length || 1)),
        near_duplicates_dropped: c.diversity.reduce((a, x) => a + x.near_duplicates_dropped, 0)},
    };
    fs.writeFileSync(path.join(dir, 'seed.json'), JSON.stringify(manifest, null, 2) + '\n');
    manifests[info.id] = {...manifest, diversity: c.diversity};
  }
  writeActs();
  return manifests;
}

/** Problems of the written collections: validation alone and together, slots, reachability, priority ties. */
export function checkCollections() {
  const problems = [];
  const ids = Object.values(COLLECTIONS).map(c => c.id);
  const validate = (circuits, label) => {
    const r = validateProgram(circuits.map(c => ({...c, role: 'knowledge'})), {authoring: true, linking: true});
    for (const p of r.problems.filter(x => x.severity !== 'warning')) problems.push(`${label}: ${p.code}: ${p.message}`);
  };
  for (const id of ids) validate(seedLayers(id), id);
  validate([...seedLayers(CONVERSATION), ...ids.flatMap(id => seedCircuits(id).map(c => ({name: `${id}:${c.file}`, text: c.text})))], 'all together');
  const text = [...seedCircuits(CONVERSATION), ...ids.flatMap(id => seedCircuits(id))].map(c => c.text).join('\n');
  const wires = parse(text).wires;
  const priorities = new Map([...text.matchAll(/holds cv_situation_priority (\w+) (-?\d+)/g)].map(m => [m[1], Number(m[2])]));
  const parts = new Map();
  const slotsOf = new Map(TAXONOMY.situations.map(s => [s.id, s.slots ?? []]));
  for (const w of wires.filter(x => x.type === 'reply')) {
    const f = k => w.fields.find(x => x.key === k)?.value.trim();
    const s = f('situation'), part = f('part') ?? 'body';
    parts.set(s, part);
    if (part === 'line') continue;
    if (!priorities.has(s)) problems.push(`${w.id}: situation ${s} has no priority`);
    const base = s.replace(/_(?:formal|playful)$/, '');
    const allowed = slotsOf.get(base);
    if (allowed) for (const m of JSON.parse(f('text')).matchAll(/\{\{([a-z_]+)\}\}/g)) if (!allowed.includes(m[1])) problems.push(`${w.id}: slot ${m[1]} is not filled for ${s}`);
  }
  // Ties (P-2.4): two situations of one part with one priority that can apply to the same turn (both triggered by message acts, or a
  // register variant and another situation) must be ordered by a cv_situation_outranks fact; otherwise the choice would be arbitrary.
  const outranks = new Set([...text.matchAll(/holds cv_situation_outranks (\w+) (\w+)/g)].map(m => `${m[1]} ${m[2]}`));
  const triggered = new Set(signalledSituations(text));
  const variants = new Set([...text.matchAll(/holds st_(?:formal|playful)_variant \w+ (\w+)/g)].map(m => m[1]));
  const base = new Map([...text.matchAll(/holds st_(?:formal|playful)_variant (\w+) (\w+)/g)].map(m => [m[2], m[1]]));
  const ordered = (a, b) => outranks.has(`${a} ${b}`) || outranks.has(`${b} ${a}`) || (base.has(a) && base.has(b) && (outranks.has(`${base.get(a)} ${base.get(b)}`) || outranks.has(`${base.get(b)} ${base.get(a)}`)));
  const contenders = [...priorities.keys()].filter(x => triggered.has(x) || variants.has(x));
  for (const a of contenders) for (const b of contenders) {
    if (a >= b || priorities.get(a) !== priorities.get(b) || parts.get(a) !== parts.get(b) || ordered(a, b)) continue;
    if (variants.has(a) && variants.has(b) && base.get(a) === base.get(b)) continue;
    if (variants.has(a) !== variants.has(b) || (triggered.has(a) && triggered.has(b))) problems.push(`unordered priority tie in part ${parts.get(a)}: ${a} and ${b} (${priorities.get(a)}); add cv_situation_outranks`);
  }
  for (const v of variants) for (const [x, p] of priorities) if (x !== v && !variants.has(x) && p === priorities.get(v) && parts.get(x) === parts.get(v) && !ordered(x, v)) problems.push(`unordered priority tie in part ${parts.get(v)}: ${v} and ${x} (${p}); add cv_situation_outranks`);
  return problems;
}

async function main() {
  const [cmd, ...args] = process.argv.slice(2);
  if (cmd === 'items') { for (const it of items()) process.stdout.write(JSON.stringify(it) + '\n'); return; }
  if (cmd === 'write') {
    const runs = (opt(args, 'runs') ?? '').split(',').filter(Boolean).map(r => path.resolve(ROOT, r));
    if (!runs.length) throw new Error('--runs DIR[,DIR...] is required');
    const drop = opt(args, 'drop') ? JSON.parse(fs.readFileSync(path.resolve(ROOT, opt(args, 'drop')), 'utf8')) : [];
    const manifests = writeCollections(buildCollections(runVariants(runs), {drop}), {runs: runs.map(r => path.relative(ROOT, r))});
    for (const [id, m] of Object.entries(manifests)) console.log(JSON.stringify({id, ...m.counts}));
    return;
  }
  if (cmd === 'acts') { writeActs(); console.log('wrote the message acts of the collections'); return; }
  if (cmd === 'check') {
    const problems = checkCollections();
    for (const p of problems) console.log(p);
    console.log(problems.length ? `${problems.length} problems` : 'ok');
    if (problems.length) process.exitCode = 1;
    return;
  }
  console.error('usage: node tools/smalltalk/build.mjs items | write --runs DIR[,DIR] [--drop FILE] | acts | check');
  process.exitCode = 2;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main().catch(e => { console.error(e.message); process.exit(1); });
