/**
 * The generated part of the self layer (config/knowledge/assistant-v1): the statistics of one base memory as facts, computed
 * deterministically from the memory's own compiled lexicon, manifest and wire statistics (never hand-written). A memory that imports
 * assistant-v1 gets this circuit when it is built (tools/assistant/memory-statistics.mjs, called by tools/world-kb/load.mjs); the same
 * input gives the same text.
 *
 *   statisticsCircuit({lexicon, manifest, stats, layers}) -> SOP text: entity_count per class, relation_fact_count per relation,
 *                                                            memory_size totals and memory_layer names
 */
const quote = s => JSON.stringify(String(s));
/** Classes of the memory with at least MIN_ENTITIES entities are listed (at most MAX_CLASSES); relations with facts (at most MAX_RELATIONS). */
export const MIN_ENTITIES = 20, MAX_CLASSES = 60, MAX_RELATIONS = 80;

export function statisticsCircuit({lexicon, manifest, stats = {}, layers = []}) {
  const byClass = new Map();
  for (const e of Object.values(lexicon.entities)) {
    const c = e.entityType;
    if (!c || c === 'class' || c === 'entity') continue;
    byClass.set(c, (byClass.get(c) ?? 0) + 1);
  }
  const classes = [...byClass].filter(([, n]) => n >= MIN_ENTITIES).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).slice(0, MAX_CLASSES);
  const relations = [...lexicon.factCounts].filter(([p, n]) => n > 0 && lexicon.predicates[p]).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).slice(0, MAX_RELATIONS);
  const sizes = [
    ['facts', manifest.facts ?? 0],
    ['entities', Object.values(lexicon.entities).filter(e => e.entityType !== 'class').length],
    ['classes', Object.values(lexicon.entities).filter(e => e.entityType === 'class').length],
    ['relations', Object.keys(lexicon.predicates).length],
    ...(stats.knowledge_files ? [['knowledge files', stats.knowledge_files]] : []),
    ...(stats.sop_wires ? [['SOP wires', stats.sop_wires]] : []),
  ];
  const lines = [`# memory statistics of ${manifest.id}: generated by tools/assistant/memory-statistics.mjs from the memory's lexicon and manifest (assistant-v1). Do not edit; rebuild.`];
  const fact = (id, holds) => lines.push(`@${id} fact\n  holds ${holds}\n  source "generated: memory statistics of ${manifest.id}"`);
  for (const [c, n] of classes) fact(`ms_entities_${c}`, `entity_count ${c} ${n}`);
  for (const [p, n] of relations) fact(`ms_relation_${p}`, `relation_fact_count ${quote(lexicon.predicates[p].labels?.en ?? p.replaceAll('_', ' '))} ${n}`);
  sizes.forEach(([kind, n], i) => fact(`ms_size_${i + 1}`, `memory_size ${quote(kind)} ${n}`));
  [...layers, manifest.name].filter(Boolean).forEach((name, i) => fact(`ms_layer_${i + 1}`, `memory_layer chatsop ${quote(name)}`));
  return lines.join('\n') + '\n';
}

/** English plural of a class label (inflection, not phrasing): "city" -> "cities", "box" -> "boxes", "film" -> "films". */
export const plural = label => /[^aeiou]y$/.test(label) ? label.slice(0, -1) + 'ies' : /(?:s|sh|ch|x|z)$/.test(label) ? label + 'es' : label + 's';

const topicCache = new WeakMap();
/** The classes the memory holds most entities of, as plural labels (the `topics` slot of the conversation layer's replies). */
export function topicsOf(lexicon, n = 4) {
  if (!lexicon?.entities) return [];
  if (!topicCache.has(lexicon)) {
    const byClass = new Map();
    for (const e of Object.values(lexicon.entities)) if (e.entityType && e.entityType !== 'class' && e.entityType !== 'entity') byClass.set(e.entityType, (byClass.get(e.entityType) ?? 0) + 1);
    const ranked = [...byClass].filter(([, count]) => count >= MIN_ENTITIES).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
    topicCache.set(lexicon, ranked.map(([c]) => plural(lexicon.entities[c]?.labels?.en ?? c.replaceAll('_', ' '))));
  }
  return topicCache.get(lexicon).slice(0, n);
}
