// Renders tools/world-kb/MAPPING.md from mapping.mjs
import fs from 'node:fs';
import {MAPPING, DERIVED, CLASSES, CLASS_VOCAB} from './mapping.mjs';
const roles = r => r.map(([a, b]) => `${a}:${b}`).join(' ');
let md = '# world-v1 mapping table (generated by `node tools/world-kb/mapping-table.mjs`, do not edit)\n\nOne row per Wikidata property read. Facts carry `source "Wikidata <item> <property>"`; Wikidata is CC0.\n\n';
md += '| Property | Predicate | Args | Kind | Scope | Note |\n| --- | --- | --- | --- | --- | --- |\n';
for (const m of MAPPING) md += `| ${m.pid} | \`${m.pred}\` | \`${roles(m.roles)}\` | ${m.kind} | ${m.scope.join(', ')} | ${m.note ?? ''}${m.only ? ' (curated values)' : ''} |\n`;
for (const d of DERIVED) md += `| ${d.source} | \`${d.pred}\` | \`${roles(d.roles)}\` | derived | all selected | ${d.note} |\n`;
md += '\n## Copula readings\n\nThe base memory imports core-min and core-en, which declare the predicates that carry a reading of "be" (`reading NAME`, `describe_rank N`): `is_a` (class, describe 1), `description` (describe 2), `has_occupation` (occupation) and `located_in` (location). world-v1 declares none of them again; its facts use their argument order. Nothing in the KnowledgeLinker names a predicate (DS021).\n';
md += '\n## Entity classes\n\n| Key | Wikidata class | Note |\n| --- | --- | --- |\n';
for (const [k, c] of Object.entries(CLASSES)) md += `| ${k} | ${c.qid} (${c.label}) | ${k in CLASS_VOCAB ? 'class entity declared by core-en when present, else by world-v1' : 'core-min class'} |\n`;
fs.writeFileSync(new URL('./MAPPING.md', import.meta.url), md);
console.log(`MAPPING.md: ${MAPPING.length} rows + ${DERIVED.length} derived`);
