// Renders tools/world-kb/MAPPING.md from mapping.mjs
import fs from 'node:fs';
import {MAPPING, DERIVED, CLASSES} from './mapping.mjs';
const roles = r => r.map(([a, b]) => `${a}:${b}`).join(' ');
let md = '# world-v1 mapping table (generated by `node tools/world-kb/mapping-table.mjs`, do not edit)\n\nOne row per Wikidata property read. Facts carry `source "Wikidata <item> <property>"`; Wikidata is CC0.\n\n';
md += '| Property | Predicate | Args | Kind | Scope | Note |\n| --- | --- | --- | --- | --- | --- |\n';
for (const m of MAPPING) md += `| ${m.pid} | \`${m.pred}\` | \`${roles(m.roles)}\` | ${m.kind} | ${m.scope.join(', ')} | ${m.note ?? ''}${m.only ? ' (curated values)' : ''} |\n`;
for (const d of DERIVED) md += `| ${d.source} | \`${d.pred}\` | \`${roles(d.roles)}\` | derived | all selected | ${d.note} |\n`;
md += '\n## Entity classes\n\n| Key | Wikidata class | Note |\n| --- | --- | --- |\n';
for (const [k, c] of Object.entries(CLASSES)) md += `| ${k} | ${c.qid} (${c.label}) |  |\n`;
fs.writeFileSync(new URL('./MAPPING.md', import.meta.url), md);
console.log(`MAPPING.md: ${MAPPING.length} rows + ${DERIVED.length} derived`);
