/**
 * Generates the host lexicon shards of world-v1 (datasets_sources/world-kb/ontology/NNNN-*.sop): one `predicate` wire per mapped
 * relation (role names and relation-phrase aliases from mapping.mjs) and one `entity` wire per item with its English and Romanian
 * labels as aliases. The lexicon format of sop/lexicon.mjs; the parser limits a file to 2,048 wires, so entities are sharded.
 * Collision policy: the most notable item of a label (most Wikipedia editions) keeps the plain label; the others are reachable
 * only through "label (description)", so a bare name never links to a minor namesake silently.
 */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {MAPPING, DERIVED, READINGS} from './mapping.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = path.join(ROOT, 'datasets_sources', 'world-kb', 'ontology');
const table = JSON.parse(fs.readFileSync(path.join(ROOT, 'datasets_sources', 'world-kb', 'entities.json'), 'utf8'));
fs.rmSync(OUT, {recursive: true, force: true});
fs.mkdirSync(OUT, {recursive: true});
const q = s => JSON.stringify(String(s).replace(/\s+/g, ' ').trim());

const preds = new Map();
for (const m of MAPPING) {
  const p = preds.get(m.pred) ?? preds.set(m.pred, {roles: m.roles, aliases: {en: new Set(), ro: new Set()}, pids: []}).get(m.pred);
  p.pids.push(m.pid);
  for (const [lang, list] of Object.entries(m.aliases ?? {})) for (const a of list) p.aliases[lang].add(a);
}
for (const d of DERIVED) if (!preds.has(d.pred)) preds.set(d.pred, {roles: d.roles, aliases: {en: new Set(), ro: new Set()}, pids: [d.source]});
let text = '# world-v1 host lexicon: predicates (generated by tools/world-kb/ontology.mjs)\n\n';
for (const [name, p] of preds) {
  text += `@${name} predicate\n`;
  for (const [role, type] of p.roles) text += `  role ${role} ${type}\n`;
  text += `  description ${q(`Wikidata ${[...new Set(p.pids)].join(', ')}`)}\n`;
  for (const lang of ['en', 'ro']) for (const a of p.aliases[lang]) text += `  alias ${lang} ${q(a)}\n`;
  const declared = READINGS[name];
  if (declared) { for (const r of declared.readings) text += `  reading ${r}\n`; if (declared.describeRank) text += `  describe_rank ${declared.describeRank}\n`; }
  text += '\n';
}
fs.writeFileSync(path.join(OUT, '0001-predicates.sop'), text);

const NEEDS_THE = new Set(['country', 'planet', 'literary_work', 'film', 'painting', 'company', 'university', 'organization', 'continent', 'language', 'currency']);
const lines = [];
let wires = 0;
for (const [sym, e] of Object.entries(table)) {
  const aliases = new Map(); // surface -> language
  const add = (lang, s) => { if (s && !aliases.has(`${lang} ${s.toLowerCase()}`)) aliases.set(`${lang} ${s.toLowerCase()}`, [lang, s]); };
  const desc = e.desc ? ` (${e.desc})` : '';
  if (e.plain) {
    add('en', e.en); if (e.ro) add('ro', e.ro);
    if (e.classes.some(c => NEEDS_THE.has(c))) { add('en', `the ${e.en}`); }
  } else add('en', `${e.en}${desc}`);
  let w = `@${sym} entity\n`;
  if (e.plain) { w += `  label en ${q(e.en)}\n`; if (e.ro) w += `  label ro ${q(e.ro)}\n`; }
  for (const [lang, s] of aliases.values()) if (!(e.plain && ((lang === 'en' && s === e.en) || (lang === 'ro' && s === e.ro)))) w += `  alias ${lang} ${q(s)}\n`;
  if (!e.plain) w += `  label en ${q(`${e.en}${desc}`)}\n`;
  lines.push(w);
}
let n = 2;
for (let i = 0; i < lines.length; i += 1800) {
  fs.writeFileSync(path.join(OUT, `${String(n++).padStart(4, '0')}-entities.sop`), lines.slice(i, i + 1800).join('\n'));
}
console.log(JSON.stringify({predicates: preds.size, entities: lines.length, shards: n - 1}));
