#!/usr/bin/env node
import fs from 'node:fs';import readline from 'node:readline/promises';import {stdin,stdout} from 'node:process';
import {cliArgs,loadJSON} from './src/util.js';import {Repository} from './src/repository.js';import {Lexicon} from './src/lexicon.js';import {Runtime} from './src/runtime.js';import {Agent} from './src/agent.js';import {publishKnowledge} from './src/ingest.js';import {parse,validateGraph,canonical} from './src/sop/parser.js';import {lowerConstraint,lowerFact,lowerRule} from './src/sop/lower.js';import {compileSMT} from './src/backends/constraints.js';import {compileProlog} from './src/solvers.js';import {instant,contains} from './src/time.js';
const args=cliArgs(),cmd=args._[0]??'help',config=loadJSON(args.config??'config/runtime.json',null);
try{
 if(cmd==='help'){console.log(`RecallSOP\n  node cli.js init [--base demo]\n  node cli.js run --file examples/query.sop [--base demo --user alice --session s1]\n  node cli.js chat [--cnl-only]\n  node cli.js fork --from demo --to copy\n  node cli.js commit|discard|stats|maintain [--base demo --user alice --session s1]
  node cli.js checkpoint-base [--base demo]
  node cli.js gc [--apply]                     # dry-run unless --apply
  node cli.js migrate|close-session [--base demo --user alice --session s1]
  node cli.js decay --steps 1 [--base demo --user alice --session s1]\n  node cli.js validate --file program.sop\n  node cli.js lexicon --text "Maria lucreaza la Alfa"\n  node cli.js compile-smt --file examples/constraint.sop\n  node cli.js compile-prolog --file examples/local.sop\n\ninit loads reviewed fictional fixtures; no LLM download is implicit.`);process.exit(0);}
 const lex=Lexicon.load(args.ontology??config.ontology??'config/ontology.sop');
 if(cmd==='validate'){const p=parse(fs.readFileSync(args.file,'utf8'));validateGraph(p);console.log(canonical(p));process.exit(0);}
 if(cmd==='lexicon'){console.log(JSON.stringify(lex.candidates(args.text??'',{language:args.language??'auto'}),null,2));process.exit(0);}
 if(cmd==='compile-smt'){const r=await new Runtime({schema:lex.predicates,policy:{allowWrite:false}}).run(fs.readFileSync(args.file,'utf8'));const c=Object.values(r.values).find(x=>x?.kind==='constraint');if(!c)throw Error('No constraint wire');const {prefix,claim}=compileSMT(c);console.log(prefix+'; claim is tested separately, not assumed true\n(push)\n(assert '+claim+')\n(check-sat)\n(pop)\n(push)\n(assert (not '+claim+'))\n(check-sat)\n(pop)');process.exit(0);}
 if(cmd==='compile-prolog'){const p=parse(fs.readFileSync(args.file,'utf8')),facts=p.wires.filter(w=>w.type==='fact').map(w=>lowerFact(w,{},lex.predicates)),rules=p.wires.filter(w=>w.type==='rule').map(w=>lowerRule(w,{},lex.predicates));const temporal=[...facts,...rules].some(x=>x.valid&&(x.valid.from!==-Infinity||x.valid.until!==Infinity));if(temporal&&!args.at)throw Error('Temporal Prolog export requires --at YYYY-MM-DD; temporal qualifiers are never silently dropped');const at=args.at?instant(args.at):0;console.log(compileProlog(facts.filter(f=>contains(f.valid,at)).map(f=>f.atom),rules.filter(r=>!r.valid||contains(r.valid,at))));process.exit(0);}
 const repo=new Repository(args.root??config.root??'state',{memory:config.memory}),base=args.base??'demo',user=args.user??'local',name=args.session??'s1';
 if(cmd==='init'){const r=publishKnowledge(repo,base,fs.readFileSync('kb/bootstrap.sop','utf8'),{schema:lex.predicates,reviewed:true,knownAt:Date.parse('2024-01-01')});console.log('Published fixture base '+base+' '+r.snapshot);process.exit(0);}
 if(cmd==='fork'){console.log(repo.fork(args.from,args.to));process.exit(0);}
 if(cmd==='checkpoint-base'){console.log(JSON.stringify(repo.checkpointBase(base),null,2));process.exit(0);}
 if(cmd==='gc'){console.log(JSON.stringify(repo.gc({dryRun:!args.apply}),null,2));process.exit(0);}
 const session=repo.session(base,user,name);
 if(cmd==='migrate'){console.log(JSON.stringify(repo.migrate(session),null,2));process.exit(0);}
 if(cmd==='close-session'){console.log(JSON.stringify(repo.closeSession(session)));process.exit(0);}
 if(cmd==='commit'){console.log(repo.commit(session));process.exit(0);}if(cmd==='discard'){repo.discard(session);console.log('Discarded uncommitted session changes.');process.exit(0);}if(cmd==='stats'){console.log(JSON.stringify(repo.stats(session),null,2));process.exit(0);}if(cmd==='maintain'){console.log(JSON.stringify(repo.maintain(session,{force:!!args.force}),null,2));process.exit(0);}if(cmd==='decay'){repo.decay(session,Number(args.steps??1));console.log(JSON.stringify(repo.stats(session),null,2));process.exit(0);}
 if(cmd==='run'){const r=await new Runtime({repo,session,schema:lex.predicates,policy:config.policy,now:args.now?Date.parse(args.now):Date.now()}).run(fs.readFileSync(args.file,'utf8'));console.log(args.json?JSON.stringify(r,null,2):(r.result.text??JSON.stringify(r.result,null,2)));process.exit(0);}
 if(cmd==='chat'){const agent=new Agent({repo,session,lexicon:lex,config}),rl=readline.createInterface({input:stdin,output:stdout});console.log('Commands: :commit :discard :sop :cnl :proof :quit. New facts remain in this session until commit.');let last;try{while(true){const text=await rl.question('> ');if(text===':quit')break;if(text===':commit'){console.log(repo.commit(session));continue;}if(text===':discard'){repo.discard(session);continue;}if(text===':sop'){console.log(last?.sop??'No previous turn');continue;}if(text===':cnl'){console.log(last?.cnl??'No previous turn');continue;}if(text===':proof'){console.log(JSON.stringify(last?.packet??null,null,2));continue;}try{last=await agent.turn(text,{rewrite:!args['cnl-only']});console.log(last.text);}catch(e){console.log('No completed answer: '+e.message);}}}finally{rl.close();}process.exit(0);}
 throw Error('Unknown command: '+cmd);
}catch(e){console.error(e.message);process.exitCode=1;}
