#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {scenarios} from './reasoning/scenarios.mjs';import {Repository} from '../memory/repository.mjs';import {publishKnowledge} from '../sop/ingest.mjs';import {Runtime} from '../sop/runtime.mjs';import {ReasoningRegistry} from '../reasoning/registry.mjs';import {canonical,parse} from '../sop/parser.mjs';import {assert,cliArgs,saveJSON} from '../lib/util.mjs';
const args=cliArgs(),engines=(args.engines??'recall-memory,holo-memory,sqlite,scan,hybrid').split(','),strategies=(args.reasoning??'reference,advanced').split(','),records=[],root=fs.mkdtempSync(path.join(os.tmpdir(),'reasoning-grid-'));
try{for(const engine of engines)for(const strategy of strategies)for(const [i,s]of scenarios().entries()){
 const memory={engine,power:10,holoMemory:{rows:256,banks:4,dimension:64,ageStepsPerNovel:0},sharding:{enabled:true,mode:'archive',maxClaimsPerShard:3,gcEveryWrites:0}};
 const repo=new Repository(path.join(root,engine,strategy,s.name),{memory});publishKnowledge(repo,'world',s.setup,{reviewed:true,knownAt:1});const session=repo.session('world','user','demo');
 const started=performance.now();const execution=await new Runtime({repo,session,now:Date.parse('2026-09-26'),policy:{retrievalStrategy:'auto',reasoningStrategy:strategy}}).run(canonical(parse(s.target)),{origin:'trusted'}),p=execution.result.packet;
 assert(p.status===s.expectedStatus,`${engine}/${strategy}/${s.name}: expected ${s.expectedStatus}, got ${p.status}`);
 const check=s.check;if(check.output)assert(execution.values[check.output]===check.value,'Wrong output '+s.name);
 if(check.objective!==undefined)assert(p.objective===check.objective,'Wrong optimum');if(check.explanations)assert(p.explanations.length===check.explanations,'Wrong explanations');if(check.testRecommended)assert(p.nextTest,'No diagnostic test');if(check.firstCandidate)assert(p.candidates[0].id===check.firstCandidate,'Wrong case');if(check.counterexamples)assert(p.patterns[0].training.counterexamples===check.counterexamples,'Wrong counterexamples');if(check.mappingScore)assert(p.mappings[0].score===check.mappingScore,'Wrong analogy');if(check.planCost)assert(p.plans[0].cost===check.planCost,'Wrong plan');if(check.hypothetical)assert(p.hypothetical,'Missing hypothetical marker');if(check.factualStatus)assert(p.factualStatus===check.factualStatus,'Wrong factual baseline');
 records.push({memory:engine,reasoning:strategy,scenario:s.name,status:p.status,complete:p.complete,route:p.route,ms:Number((performance.now()-started).toFixed(3)),assertions:'passed',cnl:execution.result.text,outputs:execution.outputs});console.log(engine+' / '+strategy+' / '+s.name+': '+p.status);
 if(engine===engines[0]&&strategy===strategies[0]){const examples=new URL('../eval/reports/current/reasoning/examples/',import.meta.url);fs.mkdirSync(examples,{recursive:true});fs.writeFileSync(new URL(s.name+'.sop',examples),canonical(parse(s.target)));saveJSON(new URL(s.name+'.json',examples),{setup:s.setup,target:canonical(parse(s.target)),packet:p,generated:execution.generated});}
}}finally{fs.rmSync(root,{recursive:true,force:true});}
const report={node:process.version,scenarios:scenarios().length,executions:records.length,passed:records.length,engines,strategies,neuralModelTested:false,records};saveJSON(args.out??new URL('../eval/reports/current/reasoning/matrix.json',import.meta.url),report);console.log('Passed '+records.length+' executions');
