import {emitAtom} from './parser.mjs';
import {emitCondition} from '../lib/conditions.mjs';
import {formatTime} from '../lib/time.mjs';
const messages={
 ro:{hypotheses:'Explicații posibile; ipotezele nu sunt confirmate.',candidates:'Candidați de explorat, nu fapte demonstrate.',patterns:'Regularități candidate măsurate pe cazurile furnizate.',plan_found:'A fost găsit un plan în modelul de acțiuni; planul nu a fost executat.',no_plan:'Nu s-a găsit un plan în spațiul finit explorat.',optimal:'Soluție optimă în modelul și domeniile declarate.',feasible_bound:'Soluție fezabilă găsită; optimalitatea nu este demonstrată.',mixed_temporal:'Afirmația și negația ei sunt susținute în intervale diferite, fără suprapunere.',supported:'Afirmația este susținută de premisele disponibile.',refuted:'Există dovezi explicite pentru negația afirmației.',both:'Există dovezi contradictorii: atât afirmația, cât și negația ei sunt susținute.',unknown:'Informațiile disponibile nu decid întrebarea.',entailed:'Afirmația rezultă din toate soluțiile permise de constrângeri.',possible:'Există cel puțin o soluție compatibilă cu afirmația.',impossible:'Nicio soluție a premiselor nu satisface afirmația.',inconsistent:'Premisele sunt incompatibile. Nu derivăm o concluzie arbitrară.',unsupported:'Această operație nu poate fi executată de backend-ul disponibil.',stored:'Afirmațiile au fost înregistrate.',incomplete:'Explorarea este incompletă; pot exista alte rezultate.',hypothetical:'Rezultat condiționat de ipotezele introduse.'},
 en:{hypotheses:'Possible explanations; assumptions are not confirmed.',candidates:'Candidates for exploration, not proven facts.',patterns:'Candidate regularities measured on supplied cases.',plan_found:'A plan was found in the action model; it has not been executed.',no_plan:'No plan was found in the explored finite state space.',optimal:'Optimal solution in the declared model and domains.',feasible_bound:'A feasible solution was found; optimality is unproven.',mixed_temporal:'The claim and its negation are supported in different, non-overlapping intervals.',supported:'The available premises support the claim.',refuted:'Explicit evidence supports the negated claim.',both:'Both the claim and its explicit negation have supporting evidence.',unknown:'The available information does not decide the question.',entailed:'The claim holds in every model of the constraints.',possible:'At least one model satisfies the claim.',impossible:'No model of the premises satisfies the claim.',inconsistent:'The premises are inconsistent; no arbitrary conclusion is accepted.',unsupported:'The available backend cannot execute this operation.',stored:'The assertions have been recorded.',incomplete:'Search is incomplete; more answers may exist.',hypothetical:'This result depends on the stated assumptions.'}
};
export function cnl(packet,language='ro'){
 const m=messages[language]??messages.en,lines=[];if(packet.hypothetical)lines.push(m.hypothetical);
 lines.push(packet.status==='clarify'?packet.text:(m[packet.status]??packet.status));
 if(packet.kind==='count')lines.push((language==='ro'?'Număr de rezultate găsite: ':'Number of retrieved results: ')+packet.count+'.');
 for(const row of packet.answers??[]){lines.push('ANSWER '+Object.entries(row.binding).map(([k,v])=>k+' = '+JSON.stringify(v)).join('; '));if(packet.query?.during&&row.valid)lines.push('VALID ['+formatTime(row.valid.from)+', '+formatTime(row.valid.until)+')');}
 for(const [name,item]of Object.entries(packet.outputProjection??{}))if(item.status==='bound')lines.push('VALUE '+name+' = '+JSON.stringify(item.value));
 for(const p of packet.proof??[])lines.push('EVIDENCE '+p.id+': '+emitAtom(p.atom)+(packet.query?.during&&p.valid?' VALID ['+formatTime(p.valid.from)+', '+formatTime(p.valid.until)+')':'')+(p.kind==='derived'?' VIA '+p.rule+' FROM '+p.premises.join(', '):' SOURCE '+p.source));
 if(packet.objective!==undefined)lines.push('OBJECTIVE '+packet.direction+' = '+packet.objective);
 for(const h of (packet.explanations??[]).slice(0,5))lines.push('HYPOTHESIS '+h.id+' COST '+h.cost+': '+h.assumptions.map(emitAtom).join(' AND '));
 if(packet.nextTest)lines.push('SUGGESTED_TEST '+packet.nextTest.query.where.map(c=>emitCondition(c,emitAtom)).join(' AND ')+'; NOT_EXECUTED');
 for(const p of (packet.patterns??[]).slice(0,5))lines.push('PATTERN '+p.id+': '+p.if.map(emitAtom).join(' AND ')+' -> '+emitAtom(p.then)+'; SUPPORT '+p.training.supportCount+'/'+p.training.opportunities+'; COUNTEREXAMPLES '+p.training.counterexamples+'; UNKNOWN '+p.training.unknown+'; NOT_A_RULE');
 for(const c of (packet.candidates??[]).slice(0,5))lines.push('CANDIDATE '+c.id+' SCORE '+c.score+'; NOT_PROBABILITY');
 for(const a of (packet.mappings??[]).slice(0,5))lines.push('ANALOGY '+JSON.stringify(a.mapping)+' MATCHED '+a.matched+'/'+a.sourceEdges+'; CANDIDATE_TRANSFER');
 for(const p of (packet.plans??[]).slice(0,5)){lines.push('PLAN COST '+p.cost+'; '+(packet.optimal?'OPTIMAL_WITHIN_MODEL':'OPTIMALITY_NOT_ESTABLISHED'));p.steps.forEach((step,i)=>lines.push('STEP '+(i+1)+' '+step.action+' '+JSON.stringify(step.binding)));}
 for(const a of packet.interventions??[])lines.push('INTERVENTION '+emitAtom(a)+'; NOT_STORED');
 if(packet.route)lines.push('ENGINE '+packet.reasoningStrategy+' / '+packet.route.backend+(packet.route.fallback?' / '+packet.route.fallback:''));
 if(packet.complete===false)lines.push(m.incomplete);
 return {kind:'cnl',language,text:lines.filter(Boolean).join('\n'),packet};
}
