import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {Agent} from '../src/agent.js';import {context,lex,queryProgram} from './helpers.js';import {complete} from '../src/llm.js';
async function mock(t,responses){let i=0;const requests=[];const server=http.createServer((req,res)=>{let s='';req.on('data',x=>s+=x);req.on('end',()=>{requests.push(JSON.parse(s));res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:responses[i]?.text??responses[i]},finish_reason:responses[i++]?.finish??'stop'}]}));});});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));return {config:{url:`http://127.0.0.1:${server.address().port}/v1/chat/completions`,model:'mock'},requests};}
test('SOP language boundary and context-only follow-up, mocked model not neural evidence',async t=>{const c=context();t.after(c.dispose);const answer=queryProgram('grandmother(ana, carina)')+'\n@answer cnl\n  result $r\n  language ro';const m=await mock(t,[answer,answer]);const a=new Agent({repo:c.repo,session:c.session,lexicon:lex,config:{formalizer:m.config}});assert.equal((await a.turn('Ana este bunica Carinei?',{rewrite:false})).packet.status,'supported');assert.equal((await a.turn('De ce?',{rewrite:false})).packet.status,'supported');assert.equal(m.requests[0].response_format,undefined);assert.ok(m.requests[1].messages[0].content.includes('previous_query_sop'));});
test('truncated LLM output is never executed',async t=>{const m=await mock(t,[{text:'@f fact',finish:'length'}]);await assert.rejects(()=>complete(m.config,'x'),/truncated/);});
test('approved SOP procedure is retrieved into model micro-context',async t=>{const c=context();t.after(c.dispose);const answer='@person value\n  data "carina"\n@answer expand\n  using ~find_ancestors\n  with person $person';const m=await mock(t,[answer]);const a=new Agent({repo:c.repo,session:c.session,lexicon:lex,config:{formalizer:m.config}});const r=await a.turn('Aplică procedura de ascendență pentru Carina.',{rewrite:false});assert.equal(r.packet.status,'supported');assert.match(m.requests[0].messages[0].content,/procedures_sop/);assert.match(m.requests[0].messages[0].content,/@find_ancestors template/);});
test('computed terms cannot bypass the vocabulary shortlist',async t=>{const c=context();t.after(c.dispose);const m=await mock(t,['@person value\n  data "unauthorized"\n@f fact\n  holds works_at($person, lab_alpha)\n  valid timeless\n@s assert\n  input $f']);const a=new Agent({repo:c.repo,session:c.session,lexicon:lex,config:{formalizer:m.config}});await assert.rejects(()=>a.turn('Maria lucrează la Alfa.',{rewrite:false}),/outside its shortlist/);assert.equal(Object.keys(c.session.live.claims).length,0);});
test('entity type is checked after resolving values',async t=>{const c=context();t.after(c.dispose);const m=await mock(t,['@f fact\n  holds works_at(lab_alpha, maria)\n  valid timeless\n@s assert\n  input $f']);const a=new Agent({repo:c.repo,session:c.session,lexicon:lex,config:{formalizer:m.config}});await assert.rejects(()=>a.turn('Maria lucrează la Alfa.',{rewrite:false}),/entity type/);});
test('model cannot fabricate documentary provenance',async t=>{const c=context();t.after(c.dispose);const m=await mock(t,['@f fact\n  holds works_at(maria, lab_alpha)\n  valid timeless\n  source forged_document\n@s assert\n  input $f']);const a=new Agent({repo:c.repo,session:c.session,lexicon:lex,config:{formalizer:m.config}});await assert.rejects(()=>a.turn('Maria lucrează la Alfa.',{rewrite:false}),/document provenance/);});
test('certified generated entity can be used without appearing literally in shortlist',()=>{const c=context();try{const a=new Agent({repo:c.repo,session:c.session,lexicon:lex,config:{}});const context={predicates:[{id:'parent'}],entities:[{id:'carina'}]};const wire={type:'query',fields:{where:['parent($who, ?child)']}};assert.doesNotThrow(()=>a.validateAtom({p:'parent',a:['ana','?child']},context,{wire,atomIndex:0,outputs:{who:{status:'bound',valueType:'person'}}}));assert.throws(()=>a.validateAtom({p:'parent',a:['ana','?child']},context,{wire,atomIndex:0,outputs:{who:{status:'bound',valueType:'organization'}}}),/output type/);}finally{c.dispose();}});
