import test from 'node:test';import assert from 'node:assert/strict';
import {parse,canonical,validateGraph,dependencies,parseAtom} from '../src/sop/parser.js';
import {lowerRule,lowerQuery,lowerConstraint} from '../src/sop/lower.js';
import {schema} from './helpers.js';
for(const [name,source]of Object.entries({duplicate:'@a value\n  data 1\n@a value\n  data 2',badField:'@a fact\n  holds parent(ana, bogdan)\n  valid timeless\n  evil 1',badIndent:'@a value\n data 1',unknownType:'@a systemExec\n  command ls',legacyVariable:'@a rule\n  when parent($x, $y)\n  then parent($x, $y)',cycle:'@a value\n  data $b\n@b value\n  data $a',undefined:'@a value\n  data $missing',reserved:'@constructor value\n  data 1'}))test('reject '+name,()=>assert.throws(()=>validateGraph(parse(source))));
test('logical variables do not create dependencies',()=>{const w=parse('@r rule\n  when parent(?x, ?y)\n  then ancestor(?x, ?y)').wires[0];assert.deepEqual(dependencies(w),{values:[],handles:[]});lowerRule(w,{},schema);});
test('quoted dollar and tilde are text',()=>assert.deepEqual(dependencies(parse('@v value\n  data "$ignored ~text"').wires[0]),{values:[],handles:[]}));
test('forward references are topologically ordered',()=>assert.deepEqual(validateGraph(parse('@b value\n  data $a + 1\n@a value\n  data 2')),['a','b']));
test('canonical roundtrip',()=>{const s='@q query\n  mode select\n  select ?x\n  where parent(?x, "Bogdan, Jr.")\n  during 2025-01-01 2026-01-01';const a=parse(s);assert.equal(canonical(parse(canonical(a))),canonical(a));});
test('predicate and argument strings are data',()=>assert.deepEqual(parseAtom('not likes(ana, "a,b")'),{p:'likes',a:['ana','a,b'],neg:true}));
test('unsafe rule is rejected',()=>assert.throws(()=>lowerRule(parse('@r rule\n  when parent(?x, ?y)\n  then parent(?x, ?z)').wires[0],{},schema)));
test('unknown predicate is not invented',()=>assert.throws(()=>lowerQuery(parse('@q query\n  where magic(ana)').wires[0],{},schema)));
test('unbound query output rejected',()=>assert.throws(()=>lowerQuery(parse('@q query\n  mode select\n  select ?z\n  where parent(?x, ?y)').wires[0],{},schema)));
test('nonlinear multiplication rejected',()=>assert.throws(()=>lowerConstraint(parse('@c constraint\n  var ?x int 0 3\n  var ?y int 0 3\n  claim ?x * ?y > 0').wires[0])));
test('temporal endpoints not guessed',()=>assert.throws(()=>lowerQuery(parse('@q query\n  where parent(ana, bogdan)\n  at 2025').wires[0],{},schema)));
